// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk09tzopRH7b9sA8uI8PXtj4pf28grSw4',
    appId: '1:644658958003:web:4ad5aee1ff12c79a18aac6',
    messagingSenderId: '644658958003',
    projectId: 'e-commerce-d19c4',
    authDomain: 'e-commerce-d19c4.firebaseapp.com',
    storageBucket: 'e-commerce-d19c4.firebasestorage.app',
    measurementId: 'G-BEJ7H48MJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDHv2IwABpXtx8F4t3RLfLVLMCnfWUmQ',
    appId: '1:644658958003:android:a0df16c806ae4ff418aac6',
    messagingSenderId: '644658958003',
    projectId: 'e-commerce-d19c4',
    storageBucket: 'e-commerce-d19c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrEZJMCjNc0UvJUDUpF8B2bTPlZl4SWxw',
    appId: '1:644658958003:ios:41dd89b16a4bc19218aac6',
    messagingSenderId: '644658958003',
    projectId: 'e-commerce-d19c4',
    storageBucket: 'e-commerce-d19c4.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrEZJMCjNc0UvJUDUpF8B2bTPlZl4SWxw',
    appId: '1:644658958003:ios:41dd89b16a4bc19218aac6',
    messagingSenderId: '644658958003',
    projectId: 'e-commerce-d19c4',
    storageBucket: 'e-commerce-d19c4.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk09tzopRH7b9sA8uI8PXtj4pf28grSw4',
    appId: '1:644658958003:web:917f86d3c001062718aac6',
    messagingSenderId: '644658958003',
    projectId: 'e-commerce-d19c4',
    authDomain: 'e-commerce-d19c4.firebaseapp.com',
    storageBucket: 'e-commerce-d19c4.firebasestorage.app',
    measurementId: 'G-Q1W8EXXR8B',
  );
}
